# -*- coding: utf-8 -*-
"""p5_constants.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19iBD3ghDZOZXE0oZ2JoB9RSlNVVZRnoF
"""

from google.colab import drive
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

WD = '/content/Drive'
drive.mount(WD)

PATH = '/content/Drive/My Drive/Colab Notebooks/1000ml/Unit2/Project5/intrusion_detection_notonehot.csv'
PREDS_DEST = '/content/Drive/My Drive/Colab Notebooks/1000ml/Unit2/Project5/predictions.csv'
ESTIMATOR = Pipeline(steps = [('scaler', StandardScaler()), 
                              ('clf', LogisticRegression(penalty = 'l2', 
                                                        class_weight = 'balanced', 
                                                        solver = 'liblinear', 
                                                        random_state=42,
                                                        C = 1e-06))])